### ISSUE TITLE
Cannot disable spell checker's dictionary via context menu

### ISSUE THREAD

**Issue by michaelkn** [d1vanov/libquentier#42] opened 2017-12-21 04:58 UTC
![context_menu](https://user-images.githubusercontent.com/25072859/34241150-7d6eec7e-e624-11e7-81de-2afde9ecba45.png)

There is the following message in logs:
ibquentier/src/note_editor/SpellChecker_p.cpp @ 114 [Info]: Can't disable dictionary: no dictionary was found for language en_&GB

**Comment by d1vanov** [comment] 2017-12-22 05:06
It's interesting how in your case the entire menu is automatically "accelerated" - I mean underlined characters within each menu entry. Neither Quentier nor libquentier has any code doing this so it must be the work of some system built-in tool - are you using any special Qt/KDE/Plasma 5 plugin doing such a thing?

In my setup I can't reproduce this issue as my menu is not accelerated but I suppose fixing this should be fairly easy - instead of passing the action's raw text as the dictionary name, should first remove all `&` symbols from it (if any). Same fix should help with #40 as well.

**Comment by michaelkn** [comment] 2017-12-22 18:40
As I understand, it's a bug in Plasma:
https://bugs.kde.org/show_bug.cgi?id=337491
https://stackoverflow.com/a/32711483

**Comment by d1vanov** [comment] 2017-12-22 18:46
The issue in KDE bugtracker was created back in 2014 - little chance to live long enough to see it fixed, should workaround instead. Only need to find all are other places where the same workaround could be applied.

**Comment by d1vanov** [comment] 2017-12-26 04:28
This one and #40 should be fixed after commit [5e4fc24](https://github.com/d1vanov/libquentier/commit/5e4fc24d79380b45f20116d195189e6900017508) in branch es [master](https://github.com/d1vanov/libquentier/commit/master) and [development](https://github.com/d1vanov/libquentier/commit/development). Also created d1vanov/quentier#155 to see if context menus on the app side are also affected by this.

**Closed by d1vanov** 2017-12-26 04:28 UTC
Labels: bug, note editor
